ui: mocha-bdd
concurrency: 1
browsers:
  # - name: chrome
  #   version: -1..latest
  # - name: firefox
  #   version: latest
  #   version: -1..latest
  - name: safari
    version: 5..latest
  - name: ie
    version: 8..latest
